name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  compile-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependecies
        run: npm ci
      - name: Compile
        run: npm run build
      - name: Test
        run: npm test
